Software_Project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from Software_Project import settings
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls')),
    url(r'^ajax/like/$', views.like, name='like'),
    url(r'^ajax/check_in/$', views.check_in, name='check_in'),
    url(r'^ajax/delete_product/$', views.delete_product, name='del_p'),
    url(r'^ajax/delete_account/$', views.delete_account, name='del_a'),
    url(r'^ajax/stock/$', views.adm_stock, name='adm_stock'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from app import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^home', views.home, name='home'),
    url(r'^signup$', views.signup, name='signup'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^productos$', views.products_administration, name='products_administration'),
    url(r'^edit_account$', views.edit_account, name='edit_account'),
    url(r'^edit_product/(?P<pid>[0-9]+)/$', views.edit_products, name='edit_products'),
    url(r'^stock$', views.stock, name='stock'),
    url(r'^vendor/(?P<pid>[0-9]+)/$', views.vendor_c, name='vendor_for_users'),
    url(r'^stats/$', views.stats, name='stats'),
]

app/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from Software_Project import settings

'''
    User:
    The primary attributes of the default user are:
        username
        password
        email
        first_name
        last_name
'''


# User extension to add usertype
class AppUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    photo = models.ImageField()
    user_type_dicc = (('C', 'Comprador'), ('VF', 'Vendedor Fijo'), ('VA', 'Vendedor Ambulante'))
    user_type = models.CharField(max_length=2, choices=user_type_dicc)


class PaymentMethod(models.Model):
    name = models.CharField(max_length=30)


# Abstract base class for both vendor types
class Vendor(models.Model):
    payment = models.ManyToManyField(PaymentMethod)
    has_stock = models.BooleanField()
    state_dicc = (('A', 'Active'), ('I', 'Inactive'))
    state = models.CharField(max_length=1, choices=state_dicc)
    # stats
    times_favorited = models.IntegerField()
    user = models.OneToOneField(AppUser, on_delete=models.CASCADE)
    lat = models.DecimalField(max_digits=10, decimal_places=2)
    lng = models.DecimalField(max_digits=10, decimal_places=2)

    def payment_str(self):
        temp = []
        for i in self.payment.values():
            temp.append(i['name'])
        return ' '.join(temp)


class AmbulantVendor(Vendor):
    pass


class StaticVendor(Vendor):
    t_start = models.TimeField()
    t_finish = models.TimeField()

    def schedule(self):
        return self.t_start.strftime('%H:%M') + '-' + self.t_finish.strftime('%H:%M')


class Buyer(models.Model):
    user = models.OneToOneField(AppUser, on_delete=models.CASCADE)
    favorites = models.ManyToManyField(Vendor)


class Category(models.Model):
    name = models.CharField(max_length=30)


# Icons are saved to avoid saving the same image many times.
class ProductIcon(models.Model):
    name = models.CharField(max_length=30)
    icon = models.ImageField()


class Product(models.Model):
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    photo = models.ImageField()
    # Foreign key as "equivalent" to ManyToOne for icon->product
    icon = models.ForeignKey(ProductIcon)
    category = models.ManyToManyField(Category)
    description = models.CharField(max_length=200)
    stock = models.IntegerField()
    price = models.IntegerField()

    def category_str(self):
        temp = []
        for i in self.category.values():
            temp.append(i['name'])
        return ' '.join(temp)


class Statistics(models.Model):
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    date = models.DateTimeField()
    amount = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'fb.js' %}"></script>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
    <!--<script src="http://materializecss.com/templates/starter-template/js/init.js"></script>-->

    {% load static %}
    <script src="{% static "js/cookies.js" %}"></script>

    <script>
        $(function () {
            $('.button-collapse').sideNav();
        });
    </script>


</head>

<body>
<div id="wrapper">
    <header>
        <div class="navbar-fixed">
            <nav class="top-nav">
                <div class="nav-wrapper teal lighten-1">
                    <a href="#" class="brand-logo right"><img
                            style="max-height: 65px!important;  padding: 8px 0!important;"
                            class="circle" src="{% static 'img/logo.png' %}"></a>
                    <div class="">
                        <a href="#" data-activates="slide-out"
                           class="left button-collapse btn-floating btn-large waves-effect waves-light"><i
                                class="material-icons">menu</i></a>
                        <a class="center page-title"></a>
                    </div>
                    <ul id="slide-out" class="side-nav fixed leftside-navigation ps-container ps-active-y">
                        <li>
                            {% block profile_info %}
                            {% endblock %}
                        </li>
                        {% block side %}
                        {% endblock %}
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

</div>
</body>

</html>

templates/app/base_vendor.html
{% extends 'app/base.html' %}
{% load static %}
{% block profile_info %}
    <div class="userView">
        <i class="material-icons right grey-text text-lighten-2"
           style="position: absolute; bottom: -0.5em; right: 0.5em; padding: 0 0 !important;">settings</i>
        <div class="background" style="height:175px;">
            <img src="{% static 'img/background4.png' %}">
        </div>
        <a href="#"><img style="margin-top: 16%;" class="circle"
                         src="/media/{{ image }}" height="42" width="42"></a>
        <a href="#"><span style="margin-left: 5%;" class="white-text name">{{ user }}</span></a>
    </div>
{% endblock %}

{% block side %}
    <li><a href="{% url 'home' %}"><i class="material-icons">home</i>Inicio</a></li>
    <li><a href="{% url 'logout' %}"><i class="material-icons">exit_to_app</i>Cerrar Sesión</a></li>
    {% if is_vendor %}
        <li><a href="{% url 'stock' %}"><i class="material-icons">list</i>Editar Stock</a></li>
        <li><a href="{% url 'stats' %}"><i class="material-icons">trending_up</i>Estadísticas</a></li>
    {% endif %}
    <li>
        <div class="divider"></div>
    </li>
    {% if not is_static and is_vendor%}
        <li><a class="subheader">Activo</a></li>
        <li>
            <script>
                $ajaxSetup();
                function check_in() {
                    $.ajax({
                        type: 'POST',
                        url: '/ajax/check_in/',
                        dataType: 'json',
                        success: function () {
                            location.reload();
                        },
                        /* revert lever if request fails */
                        error: function () {
                            const $checkbox = $('.check_in');
                            $checkbox.prop('checked', !$checkbox.prop('checked'));
                        }
                    })
                }

                $(function () {
                    $('.check_in').click(check_in);
                });

            </script>
            <div class="switch" style="margin-left: 80px;">
                <label>
                    No<input type="checkbox" class="check_in" {% if is_active %} checked {% endif %}><span
                        class="lever"></span>Sí
                </label>
            </div>
        </li>
    {% endif %}

{% endblock %}

templates/app/edit_account.html
{% extends 'app/base_vendor.html' %}
{% load static %}
{% block content %}
    <script>
        $(document).ready(function () {
            $('select').material_select();
        });

    </script>
    <script>
        $ajaxSetup();

        function borrar_cuenta() {
            console.log('click');
            $.ajax({
                type: "POST",
                url: '/ajax/delete_account/',
                dataType: 'json',
                success: function () {
                    $(location).attr('href', '/app')
                }

            });
        }
    </script>
    <div class="section"></div>

    <h4 class="teal-text" style="text-align: center;">Editar Perfil</h4>
    <div class="section"></div>

    <div class="container">
        <div class="z-depth-1 grey lighten-4 row"
             style="margin-left: 5%; margin-right: 5%; padding: 32px 48px 0 48px; border: 1px solid #EEE;">

            <form class="col s12 m12" method="post" enctype=multipart/form-data>{% csrf_token %}
                <div class='row'>
                    <div class='col s12 m12'>
                    </div>
                </div>

                <div class='row'>
                    <div class='input-field col s12 m12'>
                        &ensp;Nombre :
                        <div class="input-field inline ">
                            {{ form.name }}
                            <label style="text-align: center" for='name'></label>
                        </div>
                    </div>
                </div>
                <div class='row'>
                    <div class='input-field col s12 m12'>
                        &ensp;Apellido :
                        <div class="input-field inline ">
                            {{ form.last_name }}
                            <label style="text-align: center" for='last_name'></label>
                        </div>
                    </div>
                </div>
                {% if is_vendor %}
                    <div class='row'>
                        <div class='input-field col s12 m12'>
                            &ensp;Métodos de pago :
                            {{ form.payment }}
                        </div>
                    </div>
                {% endif %}

                {% if is_static and is_vendor %}
                    <div class='row'>
                        <div class='input-field col s12 m12'>
                            &ensp;Hora de Inicio :
                            {{ form.t_init }}
                        </div>
                    </div>
                    <div class='row'>
                        <div class='input-field col s12 m12'>
                            &ensp;Hora de Termino :
                            {{ form.t_finish }}
                        </div>
                    </div>
                {% endif %}
                <div>
                    <div class="col s12">
                        <p>Foto de Perfil</p>
                    </div>
                </div>
                <div id="file-upload" class="row">
                    <!--Default version-->

                    <div class="col s12">
                        <div class="dropify-wrapper touch-fallback">
                            <div class="dropify-message">
                                <div class="row">
                                    <div class="col s4"></div>
                                    <div class="col s4">
                                        <i class="material-icons tiny">cloud_upload</i>
                                    </div>
                                    <div class="col s4"></div>
                                </div>
                                <p class="center-align">Arrastre y suelte un archivo aquí o haga click</p>
                                <p class="dropify-error center-align">Sorry, this file is too large</p>
                            </div>
                            <!--<input type="file" id="input-file-now" class="dropify" data-default-file="">-->
                            {{ form.photo }}
                            <button type="button" class="dropify-clear">Remove</button>
                            <div class="dropify-preview"><span class="dropify-render"></span>
                                <div class="dropify-infos">
                                    <div class="dropify-infos-inner">
                                        <p class="dropify-filename">

                                            <!--<span class="file-icon"></span>-->
                                            <span class="dropify-filename-inner"></span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class='row'>
                    <a class='col m4 btn btn-large waves-effect button red'
                       onclick="borrar_cuenta()">Borrar Cuenta<i
                            class="material-icons right">delete</i></a>
                    <a class='col m4 btn btn-large waves-effect button teal red'
                       href="{% url 'home' %}">Cancelar<i
                            class="material-icons right">not_interested</i></a>
                    <button class='col m4 btn btn-large waves-effect button teal green' type="submit">Modificar<i
                            class="material-icons right">done</i></button>
                </div>
            </form>
        </div>
    </div>


{% endblock %}

templates/app/edit_product.html
{% extends 'app/base_vendor.html' %}
{% load static %}

{% block content %}
    <script>
        $ajaxSetup();

        function borrar_producto() {
            console.log('click');
            $.ajax({
                type: "POST",
                url: '/ajax/delete_product/',
                data: {
                    id: {{ id }}
                },
                dataType: 'json',
                success: function () {
                    $(location).attr('href','/app/home')
                }
            });
        }
    </script>
    <div class="section"></div>

    <h4 class="teal-text" style="text-align: center;">Editar Item</h4>
    <div class="section"></div>

    <div class="container">
        <div class="z-depth-1 grey lighten-4 row"
             style="margin-left: 5%; margin-right: 5%; padding: 32px 48px 0 48px; border: 1px solid #EEE;">

            <form class="col s12 m12" method="post" enctype = multipart/form-data>{% csrf_token %}
                <div class='row'>
                    <div class='col s16 m12'>
                    </div>
                </div>
                <div class="row">
                    <div class="col m6">
                        <div class="card">
                            <div class="card-image">
                                <img src="/media/{{ photo }}" style="width: 100%; height: auto">
                            </div>
                        </div>
                    </div>
                    <div class="col m6">
                        <div class='row'>
                            <div class='input-field col s12 m12'>
                                &ensp;Nombre del producto:
                                <div class="input-field inline ">
                                    {{ form.name }}
                                    <label style="text-align: center" for='name'></label>
                                </div>
                            </div>
                        </div>

                        <div class='row'>
                            <div class='input-field col s12 m12'>
                                &ensp;Precio del producto:
                                <div class="input-field inline">
                                    {{ form.price }}
                                    <label style="text-align: center" for='price'></label>
                                </div>
                            </div>
                        </div>
                        <div class='row'>
                            <div class='input-field col s12 m12'>
                                &ensp;Stock del producto:
                                <div class="input-field inline">
                                    {{ form.stock }}
                                    <label style="text-align: center" for='stock'></label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col s12">
                        <div class="row">
                            <div class="input-field col s12 m12">
                                {{ form.des}}
                                <label for="icon_prefix2">
                                    <div class="row">
                                        <div class="col s6"><i class="material-icons prefix col s3">mode_edit</i></div>
                                        <div class="col s6">Descripción</div>
                                    </div>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="section">
                    <p>Cambiar Foto:</p>
                </div>
                <div id="file-upload" class="row">
                    <!--Default version-->
                    <div class="col s12">
                        <div class="dropify-wrapper touch-fallback">
                            <div class="dropify-message">
                                <div class="row">
                                    <div class="col s4"></div>
                                    <div class="col s4">
                                        <i class="material-icons tiny">cloud_upload</i>
                                    </div>
                                    <div class="col s4"></div>
                                </div>
                                <p class="center-align">Arrastre y suelte un archivo aquí o haga click</p>
                                <p class="dropify-error center-align">Sorry, this file is too large</p>
                            </div>
                            {{ form.photo }}
                            <button type="button" class="dropify-clear">Remove</button>
                            <div class="dropify-preview"><span class="dropify-render"></span>
                                <div class="dropify-infos">
                                    <div class="dropify-infos-inner">
                                        <p class="dropify-filename">

                                            <!--<span class="file-icon"></span>-->
                                            <span class="dropify-filename-inner"></span></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                 <div class='row'>
                     <a href="{% url 'home' %}" class='col m4 btn btn-large waves-effect button red'
                      onclick="borrar_producto()" >Borrar<i
                            class="material-icons right">delete</i></a>
                    <a class='col m4 btn btn-large waves-effect button teal red'
                       href="{% url 'home' %}">Cancelar<i
                            class="material-icons right">not_interested</i></a>
                    <button class='col m4 btn btn-large waves-effect button teal green' type="submit">Modificar<i
                            class="material-icons right">done</i></button>
                </div>
            </form>
        </div>
    </div>


{% endblock %}

templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block profile_info %}
    <div class="userView">
        <i class="material-icons right grey-text text-lighten-2"
           style="position: absolute; bottom: -0.5em; right: 0.5em; padding: 0 0 !important;">settings</i>
        <div class="background" style="height:175px;">
            <img src="{% static 'img/background4.png' %}">
        </div>
        <a href="#"><img style="margin-top: 16%;" class="circle"
                              src="{% static 'img/AvatarPenguin.png' %}"></a>
        <a href="#"><span style="margin-left: 5%;" class="white-text name">Invitado</span></a>
    </div>
{% endblock %}

{% block side %}
    <li><a href="{% url 'index' %}"><i class="material-icons">home</i>Inicio</a></li>
    <li><a href="{% url 'login' %}"><i class="material-icons">account_circle</i>Iniciar Sesión</a></li>
    <li>
        <div class="divider"></div>
    </li>
{% endblock %}
{% block content %}
    <div class="section"></div>
        <div class="section"></div>

        <h5 style="text-align: center;" class="teal-text">Inicia Sesión</h5>
        <div class="section"></div>

        <div class="container">
            <div class="z-depth-1 grey lighten-4 row"
                 style="margin-left: 5%; margin-right: 5%; padding: 32px 48px 0 48px; border: 1px solid #EEE;">

                <form class="col s12" method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class='row'>
                        <div class='input-field col s12'>
                            {{ form.username }}
                            <label style="text-align: center;" for='email'>Ingresa tu Nombre de Usuario</label>
                        </div>
                    </div>

                    <div class='row'>
                        <div class='input-field col s12'>
                            {{ form.password }}
                            <label style="text-align: center;" for='password'>Ingresa tu contraseña</label>
                        </div>
                        <label style='float: right;'>
                            <a class='red-text text-accent-2' href='#'><b>¿Olvidaste tu contraseña?</b></a>
                        </label>
                    </div>
                    <div class='row'>
                        <div class='col s12'>
                            <a class='red-text text-accent-2'><b>{{ login_message }}</b></a>

                        </div>
                    </div>

                    <div class='row'>
                        <button type='submit' name='btn_login' class='col l6 offset-l3 btn btn-large waves-effect teal'>
                            Iniciar sesión
                        </button>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}"/>

                </form>
            </div>
        </div>
        <div style="text-align: center;"><a class="grey-text">¿Aún no tienes cuenta?</a> <a href="{% url 'signup' %}">
            Regístrate</a></div>


        <div class="section"></div>
        <div class="section"></div>

{% endblock %}

templates/app/signup.html
{% extends 'app/base.html' %}
{% load static %}
{% block profile_info %}
    <div class="userView">
        <i class="material-icons right grey-text text-lighten-2"
           style="position: absolute; bottom: -0.5em; right: 0.5em; padding: 0 0 !important;">settings</i>
        <div class="background" style="height:175px;">
            <img src="{% static 'img/background4.png' %}">
        </div>
        <a href="#"><img style="margin-top: 16%;" class="circle"
                              src="{% static 'img/AvatarPenguin.png' %}"></a>
        <a href="#"><span style="margin-left: 5%;" class="white-text name">Invitado</span></a>
    </div>
{% endblock %}

{% block side %}
    <li><a href="{% url 'index' %}"><i class="material-icons">home</i>Inicio</a></li>
    <li><a href="{% url 'login' %}"><i class="material-icons">account_circle</i>Iniciar Sesión</a></li>
    <li>
        <div class="divider"></div>
    </li>
{% endblock %}

{% block content %}

    <script>
        $(document).ready(function () {
            $('select').material_select();
        });

        $(function () {
            $('#id_user_type').on('change', function () {
                var selected = $('#id_user_type').find('option:selected').val();
                if (selected == 'VF') {
                    $('#hours').slideDown();
                    $('#vendor_info').slideDown();
                }
                if (selected == 'VA') {
                    $('#hours').slideUp();
                    $('#vendor_info').slideDown();
                }
                if (selected == 'C') {
                    $('#hours').slideUp();
                    $('#vendor_info').slideUp();
                }
            });
        });


    </script>
    <div style="padding-top: 2em"></div>
    <h5 class="teal-text" style="text-align: center;">¡Regístrate!</h5>
    <div class="container">
        <div class="z-depth-1 grey lighten-4 row"
             style="margin : 5%; padding: 1.6em;">

            <form class="col s12 m12" method="post"
                enctype = multipart/form-data>{%csrf_token%}
                <div class='row'>
                    <div class='col s12 m12'>
                    </div>
                </div>

                <div class="input-field col s12 m12">
                    {{ form.user_type }}
                    <label>Tipo de Usuario</label>
                </div>


                <div class='row'>
                    <div class='input-field col s12 m12'>
                        {{ form.username }}
                        <label style="text-align: center" for='username'>Ingresa tu nombre de Usuario</label>
                    </div>
                </div>


                <div class='row'>
                    <div class='input-field col s12 m12'>
                        {{ form.name }}
                        <label style="text-align: center" for='nombre'>Ingresa tu nombre</label>
                    </div>
                </div>

                <div class='row'>
                    <div class='input-field col s12 m12'>
                        {{ form.last_name }}
                        <label style="text-align: center" for='nombre'>Ingresa tu apellido</label>
                    </div>
                </div>

                <div class='row'>
                    <div class='input-field col s12 m12'>
                        {{ form.email }}
                        <label style="text-align: center" for='email'>Ingresa tu e-mail</label>
                    </div>
                </div>

                <div class="row" id="hours" hidden>
                    <div class="col s12">
                        <div class="row">
                            <div class="input-field col s6">
                                <i class="material-icons prefix">alarm</i>
                                {{form.t_init}}
                                <label for="icon_prefix">Hora inicial</label>
                            </div>
                            <div class="input-field col s6">
                                <i class="material-icons prefix">alarm</i>
                                {{form.t_finish}}
                                <label for="icon_telephone">Hora final</label>
                            </div>
                        </div>
                    </div>
                </div>


                <div>
                    Insertar foto:
                </div>
                <div>
                    {{form.photo}}

                </div>

                <div id="vendor_info" hidden>
                    <div class='row'>
                        <div class='input-field col s12 m12'>
                            Seleccione sus formas de pago:
                       <div>
                        {{form.payment}}
                        </div>
                        </div>
                    </div>

                </div>

                <div class='row'>
                    <div class='input-field col s12 m12'>
                        {{ form.password }}
                        <label style="text-align: center" for='password'>Ingresa tu contraseña</label>
                    </div>
                </div>


                <div class='row'>
                    <div class='input-field col s12 m12'>
                        {{ form.repassword }}
                        <label style="text-align: center" for='password2'>Repite tu contraseña</label>
                    </div>
                </div>

                <div class='row'>
                    <button type='submit' name='btn_login' class='col l6 offset-l3 btn btn-large waves-effect teal'>
                        Registrarse
                    </button>
                </div>

            </form>
        </div>
    </div>
    <div style="text-align: center;"><a class="grey-text"> ¿Ya tienes una cuenta? </a><a
            href="{% url 'login' %}">Inicia sesión</a></div>

    <div style="padding-top: 4em"></div>

{% endblock %}